---
repos:
    - repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.16.0
      hooks:
          - id: yamllint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: flake8
